"""
NLP Fraud Detector - Layer 4 of Fraud Detection System
Detects fake reviews, rating manipulation, and contradictory feedback
Author: Member 3 (You!)
"""

import re
from typing import Dict, Any, List, Optional
from datetime import datetime

try:
    from transformers import pipeline
    TRANSFORMERS_AVAILABLE = True
except Exception:
    TRANSFORMERS_AVAILABLE = False
    print("⚠️ transformers not installed. Using heuristic fallback.")

from .base_detector import FraudResult, FraudAction


class NLPFraudDetector:
    """
    Detects fraudulent reviews and rating manipulation
    Uses BERT for sentiment analysis + heuristic rules
    """
    
    def __init__(self):
        self.sentiment_analyzer = None
        self.model_loaded = False
        self._load_model()
    
    def _load_model(self):
        """Load BERT model for sentiment analysis if available"""
        if not TRANSFORMERS_AVAILABLE:
            print("ℹ️ transformers not installed. Using heuristic fallback.")
            return
        
        try:
            # Load a small, fast BERT model for sentiment analysis
            self.sentiment_analyzer = pipeline(
                "sentiment-analysis",
                model="distilbert-base-uncased-finetuned-sst-2-english",
                device=-1  # Use CPU
            )
            self.model_loaded = True
            print("✅ BERT sentiment model loaded for NLP fraud detection!")
        except Exception as e:
            print(f"⚠️ Could not load BERT model: {e}")
            print("   Using heuristic fallback.")
    
    def detect(self, review_text: str, delivery_data: Optional[Dict] = None) -> FraudResult:
        """
        Detect if a review is fraudulent or manipulated
        
        Args:
            review_text: The customer review text
            delivery_data: Optional dict with delivery info (on_time, rating, etc.)
        
        Returns:
            FraudResult with fraud_score, action, reason, confidence
        """
        
        fraud_score = 0
        reasons = []
        
        # Check 1: Empty or too short reviews (suspicious)
        if len(review_text.strip()) < 10:
            fraud_score += 25
            reasons.append("Review too short (<10 characters)")
        
        # Check 2: All caps or excessive punctuation
        if review_text.isupper():
            fraud_score += 15
            reasons.append("Review in all caps (possible bot)")
        
        if review_text.count('!') > 3:
            fraud_score += 10
            reasons.append("Excessive exclamation marks")
        
        # Check 3: Repetitive patterns (bot-generated)
        words = review_text.lower().split()
        unique_ratio = len(set(words)) / len(words) if words else 1
        if unique_ratio < 0.3:  # Less than 30% unique words
            fraud_score += 30
            reasons.append("Repetitive text pattern (possible bot)")
        
        # Check 4: Contradiction detection (if delivery data available)
        if delivery_data:
            # Check if negative review for on-time delivery
            sentiment = self._get_sentiment(review_text)
            
            if sentiment == "NEGATIVE" and delivery_data.get('on_time', True):
                fraud_score += 40
                reasons.append("Contradiction: Negative review for on-time delivery")
            
            # Check if rating mismatch
            if delivery_data.get('rating', 5) >= 4 and sentiment == "NEGATIVE":
                fraud_score += 35
                reasons.append("Contradiction: High rating but negative sentiment")
        
        # Check 5: AI-generated text detection (heuristic)
        ai_patterns = [
            r'as an ai', r'i am an ai', r'generated by',
            r'as a language model', r'prompt:'
        ]
        for pattern in ai_patterns:
            if re.search(pattern, review_text.lower()):
                fraud_score += 50
                reasons.append(f"AI-generated text pattern detected: '{pattern}'")
                break
        
        # Check 6: Review flooding (same text repeated)
        if delivery_data and delivery_data.get('similar_reviews_count', 0) > 5:
            fraud_score += 40
            reasons.append(f"Review flooding: {delivery_data['similar_reviews_count']} similar reviews")
        
        # Cap fraud score
        fraud_score = min(fraud_score, 100)
        
        # Determine action
        if fraud_score >= 60:
            action = FraudAction.REJECT
        elif fraud_score >= 30:
            action = FraudAction.REVIEW
        else:
            action = FraudAction.APPROVE
        
        reason = " | ".join(reasons) if reasons else "No fraud indicators detected"
        
        return FraudResult(
            fraud_score=fraud_score,
            action=action,
            reason=reason,
            confidence=80 if fraud_score > 0 else 90,
            detector_name="NLPFraudDetector",
            metadata={
                "review_length": len(review_text),
                "unique_word_ratio": unique_ratio if 'unique_ratio' in locals() else None,
                "bert_loaded": self.model_loaded
            }
        )
    
    def _get_sentiment(self, text: str) -> str:
        """Get sentiment using BERT or simple keyword matching"""
        
        if self.model_loaded and self.sentiment_analyzer:
            try:
                result = self.sentiment_analyzer(text[:512])[0]  # BERT has 512 token limit
                return result['label'].upper()
            except Exception:
                pass
        
        # Fallback: Keyword-based sentiment
        positive_words = ['good', 'great', 'excellent', 'amazing', 'fast', 'perfect', 'awesome']
        negative_words = ['bad', 'poor', 'terrible', 'slow', 'late', 'awful', 'worst']
        
        text_lower = text.lower()
        pos_count = sum(1 for w in positive_words if w in text_lower)
        neg_count = sum(1 for w in negative_words if w in text_lower)
        
        if neg_count > pos_count:
            return "NEGATIVE"
        elif pos_count > neg_count:
            return "POSITIVE"
        else:
            return "NEUTRAL"


# Singleton instance
nlp_detector = NLPFraudDetector()
